version: "3.6"

services:
  diary-main:
    image: jungko-main-application
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "diary-application"
    ports:
      - "8080:8080"
    volumes:
      - $HOME/logs/:/logs/
    networks:
      - diary

  diary-redis:
    image: redis:latest
    restart: always
    container_name: "diary-redis"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10
    networks:
      - diary

networks:
  diary:
    driver: bridge

volumes:
  mariadb-data:
