version: "3.6"

services:
  jungko-main-application:
    image: jungko-main-application
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "jungko-main-application"
    ports:
      - "8080:8080"
    volumes:
      - $HOME/logs/:/logs/
      - $HOME/server-config/main/resources/:/resources/
    networks:
      - jungko

networks:
  jungko:
    driver: bridge
