version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: jungko
      MARIADB_PASSWORD: P4ssword!
      MARIADB_DATABASE: jungko
      MARIADB_ROOT_PASSWORD: P4ssword!
      MYSQL_TCP_PORT: 3306
      MYSQL_UNIX_PORT: 3306
    ports:
      - 3307:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--silent",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pP4ssword!",
        ]
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:latest
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80

