spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mariadb://localhost/jungko-server?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:jungko-server}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
springdoc:
  pathsToMatch: /api/**
